name: Fuzz Parser

on:
  push:
    branches:
      - '**'
    paths:
      - src/scanner.c
  pull_request:
    branches:
      - 'main'
    paths:
      - src/scanner.c
  workflow_dispatch:

jobs:
  test:
    name: Parser fuzzing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - uses: vigoux/tree-sitter-fuzz-action@v1
        with:
          language: angular
          external-scanner: src/scanner.c
          time: 60
